apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-log
spec:
  selector:
    matchLabels:
      app: python-log
  template:
    metadata:
      labels:
        app: python-log
    spec:
      containers:
      - name: python
        image: 192.168.154.128:5000/python-web-app-redis
---
apiVersion: v1
kind: Service
metadata:
  name: service-python-log
spec:
  type: NodePort
  selector:
      app: python-log
  ports:
  - port: 8000
