apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: $NS
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
      - /var/log/gunicorn_*
    output.elasticsearch:
      hosts: ["http://elasticsearch.default.svc:9200"]
      username: "elastic"
      password: "asus1650"
