apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-python-app
  namespace: $NS
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
