apiVersion: v1
kind: Service
metadata:
  name: service-python-log
  namespace: $NS
  labels:
    app: python-log
spec:
  type: NodePort
  selector:
      app: python-log
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
